- name: install tvheadend and tools
  apt:
    name: '{{item}}'
  loop:
    - tvheadend
    - python3-lxml
    - python3-configobj
    - socat

# get the home of the tvheadend user
- getent:
    database: passwd
    key: hts
    split: ':'
- debug:
    var: getent_passwd

- file:
    path: '{{item}}'
    state: directory
    owner: hts
    group: video
    mode: 0700
  loop:
    - /{{getent_passwd['hts'][4]}}/channels

- name: add channel script
  copy:
    src: prepare_channels.py
    dest: /{{getent_passwd['hts'][4]}}/channels/prepare_channels.py
    owner: hts
    group: video
    mode: 0700

- name: add channel config
  copy:
    src: prepare_channels.conf
    dest: /{{getent_passwd['hts'][4]}}/channels/prepare_channels.conf
    owner: hts
    group: video
    mode: 0600

- name: create channel playlist
  command: /{{getent_passwd['hts'][4]}}/channels/prepare_channels.py
  args:
    chdir: /{{getent_passwd['hts'][4]}}/channels
    creates: /{{getent_passwd['hts'][4]}}/channels/data/tv7playlist.m3u

- name: add superuser for tvheadend
  copy:
    src: superuser
    dest: /{{getent_passwd['hts'][4]}}/.hts/tvheadend/superuser
    owner: hts
    group: hts
    mode: 0600
  notify: restart_tvheadend

- name: disable startup wizard for tvheadend
  lineinfile:
    path: /{{getent_passwd['hts'][4]}}/.hts/tvheadend/config
    regexp: '(?:(?<=\s)|^)\"wizard\"'
    state: absent
  notify: restart_tvheadend

- file:
    path: '{{item}}'
    state: directory
    owner: hts
    group: video
    mode: 0700
  loop:
    - /{{getent_passwd['hts'][4]}}/.hts/tvheadend/input
    - /{{getent_passwd['hts'][4]}}/.hts/tvheadend/input/iptv
    - /{{getent_passwd['hts'][4]}}/.hts/tvheadend/input/iptv/networks
    - /{{getent_passwd['hts'][4]}}/.hts/tvheadend/input/iptv/networks/3cfd08f7ff52f92ea3f2f3e63c30e74a

- name: add tv7 input config for tvheadend
  template:
    src: input-config-tv7.j2
    dest: /{{getent_passwd['hts'][4]}}/.hts/tvheadend/input/iptv/networks/3cfd08f7ff52f92ea3f2f3e63c30e74a/config
    owner: hts
    group: video
    mode: 0600
  notify: restart_tvheadend

- name: enable and start tvheadend service(s)
  systemd:
    enabled: yes
    state: started
    name: '{{item}}'
  loop:
    - tvheadend

- name: enable the bouquet created by tvheadend
  shell: sed -i 's/"enabled"{{':'}} false/"enabled"{{':'}} true/g' $(grep 3cfd08f7ff52f92ea3f2f3e63c30e74a {{getent_passwd['hts'][4]}}/.hts/tvheadend/bouquet/* |cut -d "{{':'}}" -f1); touch bouquet-enabled.done
  args:
    chdir: /{{getent_passwd['hts'][4]}}/channels
    creates: bouquet-enabled.done
    warn: false
  notify: restart_tvheadend

- file:
    path: '{{item}}'
    state: directory
    owner: hts
    group: video
    mode: 0700
  loop:
    - /{{getent_passwd['hts'][4]}}/.hts/tvheadend/epggrab

- name: add epg grab config
  copy:
    src: epggrab-config
    dest: /{{getent_passwd['hts'][4]}}/.hts/tvheadend/epggrab/config
    owner: hts
    group: video
    mode: 0600
  notify: restart_tvheadend

- name: add epg script
  copy:
    src: getepg.sh
    dest: /{{getent_passwd['hts'][4]}}/channels/getepg.sh
    owner: hts
    group: video
    mode: 0700

- name: add cron job to update the epg
  cron:
    name: "epg update"
    minute: "0"
    hour: "4"
    job: "{{getent_passwd['hts'][4]}}/channels/getepg.sh"

- name: import epg data
  command: /{{getent_passwd['hts'][4]}}/channels/getepg.sh
  args:
    chdir: /{{getent_passwd['hts'][4]}}/channels
